"""
Daily compression report generator for context-compressor.

Primary data source is the ``daily_stats`` table in the shared SQLite DB.
On first request of the day (or via ``persist_daily_stats()``), raw entries
from ``cold_entries`` are aggregated and materialised into ``daily_stats``.
Subsequent reads hit the pre-aggregated table (sub-millisecond).

Markdown / JSON files are purely on-demand artefacts generated by the
``--save`` flag and are **not** the canonical store.

Usage::

    py daily_report.py                     # Today's report (stdout, from DB)
    py daily_report.py --date 2026-06-11   # Specific date
    py daily_report.py --week              # This week (Mon → today)
    py daily_report.py --month             # This month (1st → today)
    py daily_report.py --range 2026-06-01..2026-06-10
    py daily_report.py --json              # JSON output
    py daily_report.py --save              # Save MD+JSON to reports/ (on-demand)
    py daily_report.py --persist           # Persist today's raw entries →
                                           #   daily_stats (idempotent)

Programmatic usage::

    from daily_report import persist_daily_stats, generate_report, query_stats
"""

from __future__ import annotations

import argparse
import json
import os
import sys
import sqlite3
import time
from datetime import date as _date, datetime, timedelta
from pathlib import Path

# ── Ensure compress module is importable from same directory ──────────────
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
if _SCRIPT_DIR not in sys.path:
    sys.path.insert(0, _SCRIPT_DIR)

from compress import _resolve_workspace  # noqa: E402
from typing import Any


# ── Constants ───────────────────────────────────────────────────────────────

ESTIMATED_SAVED_PCT: dict[str, float] = {
    "code": 60.0, "json": 80.0, "lint": 40.0,
    "search": 70.0, "log": 50.0, "diff": 30.0,
    "text": 50.0, "unknown": 50.0,
}

TYPE_LABELS: dict[str, str] = {
    "code": "Code", "json": "JSON", "lint": "Lint",
    "search": "Search", "log": "Log", "diff": "Diff",
    "text": "Text", "unknown": "Other",
}

COST_PER_M_TOKENS = 3.0  # Claude Sonnet ~$3/M input tokens


# ── Path resolution ─────────────────────────────────────────────────────────

def _resolve_db_path() -> str:
    workspace = _resolve_workspace()
    return str(
        Path(workspace) / ".codebuddy" / "skills" / "context-compressor"
        / "cache" / "ccr_shared_cold.db"
    )


def _resolve_report_dir() -> str:
    workspace = _resolve_workspace()
    return str(
        Path(workspace) / ".codebuddy" / "skills"
        / "context-compressor" / "reports"
    )


# ── Database helpers ────────────────────────────────────────────────────────

def _ensure_schema(conn: sqlite3.Connection) -> None:
    """Create ``daily_stats`` table and indexes if missing."""
    conn.executescript("""
        CREATE TABLE IF NOT EXISTS daily_stats (
            date         TEXT NOT NULL,
            content_type TEXT NOT NULL DEFAULT 'unknown',
            entry_count  INTEGER DEFAULT 0,
            total_size_bytes INTEGER DEFAULT 0,
            estimated_original_tokens INTEGER DEFAULT 0,
            estimated_saved_tokens   INTEGER DEFAULT 0,
            PRIMARY KEY (date, content_type)
        );
        CREATE INDEX IF NOT EXISTS idx_daily_stats_date
            ON daily_stats(date);
    """)
    conn.commit()


def _boot_epoch() -> float:
    """Estimate boot epoch so monotonic timestamps can be mapped to wall-clock."""
    return time.time() - time.monotonic()


def _mono_to_date(stored: float) -> str:
    """Convert a monotonic timestamp to an ISO date string."""
    return _date.fromtimestamp(_boot_epoch() + stored).isoformat()


# ── Persist: raw entries → daily_stats materialisation ──────────────────────

def persist_daily_stats(target_date: str | None = None) -> bool:
    """Aggregate today's ``cold_entries`` into ``daily_stats`` (idempotent).

    Must be called at least once per day (typically from the *Stop* hook) so
    that ``query_stats`` and ``generate_report`` have pre-aggregated data.

    Returns ``True`` on success, ``False`` if the DB is missing or an error
    occurs.
    """
    db_path = _resolve_db_path()
    if not os.path.exists(db_path):
        return False

    if target_date is None:
        target_date = _date.today().isoformat()

    try:
        conn = sqlite3.connect(db_path)
        conn.row_factory = sqlite3.Row
        _ensure_schema(conn)

        boot = _boot_epoch()

        rows = conn.execute(
            "SELECT content_type, size_bytes, stored_at FROM cold_entries"
        ).fetchall()

        # Aggregate by content_type for the target date only.
        ag: dict[str, dict[str, Any]] = {}
        for r in rows:
            ctype = r["content_type"] or "unknown"
            size = r["size_bytes"] or 0
            entry_date = _date.fromtimestamp(boot + r["stored_at"]).isoformat()
            if entry_date != target_date:
                continue

            if ctype not in ag:
                ag[ctype] = {"entry_count": 0, "total_size_bytes": 0}
            ag[ctype]["entry_count"] += 1
            ag[ctype]["total_size_bytes"] += size

        # Write (INSERT OR REPLACE for idempotency).
        for ctype, a in ag.items():
            original_tokens = max(1, a["total_size_bytes"] // 4)
            saved_pct = ESTIMATED_SAVED_PCT.get(ctype, 50.0)
            saved_tokens = int(original_tokens * saved_pct / 100)

            conn.execute(
                "INSERT OR REPLACE INTO daily_stats "
                "(date, content_type, entry_count, total_size_bytes, "
                " estimated_original_tokens, estimated_saved_tokens) "
                "VALUES (?, ?, ?, ?, ?, ?)",
                (
                    target_date, ctype, a["entry_count"],
                    a["total_size_bytes"], original_tokens, saved_tokens,
                ),
            )

        conn.commit()
        conn.close()
        return True

    except Exception:
        return False


# ── Query: read from daily_stats ────────────────────────────────────────────

def query_stats(
    date_from: str,
    date_to: str | None = None,
) -> list[dict[str, Any]]:
    """Query pre-aggregated stats from ``daily_stats`` for a date range.

    Returns a list of per-type dicts aggregated across the range, sorted by
    ``estimated_saved_tokens`` descending.
    """
    if date_to is None:
        date_to = date_from

    db_path = _resolve_db_path()
    if not os.path.exists(db_path):
        return []

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row

    try:
        _ensure_schema(conn)

        rows = conn.execute(
            "SELECT content_type, "
            "       SUM(entry_count) AS entry_count, "
            "       SUM(total_size_bytes) AS total_size_bytes, "
            "       SUM(estimated_original_tokens) AS estimated_original_tokens, "
            "       SUM(estimated_saved_tokens) AS estimated_saved_tokens "
            "FROM daily_stats "
            "WHERE date >= ? AND date <= ? "
            "GROUP BY content_type "
            "ORDER BY estimated_saved_tokens DESC",
            (date_from, date_to),
        ).fetchall()

        if not rows:
            # No pre-aggregated data — fall back to raw cold_entries.
            conn.close()
            return _aggregate_from_cold(date_from, date_to)

        results: list[dict[str, Any]] = []
        for r in rows:
            ctype = r["content_type"] or "unknown"
            original = r["estimated_original_tokens"]
            saved = r["estimated_saved_tokens"]
            pct = ESTIMATED_SAVED_PCT.get(ctype, 50.0)

            results.append({
                "content_type": ctype,
                "label": TYPE_LABELS.get(ctype, ctype),
                "entry_count": r["entry_count"],
                "total_size_bytes": r["total_size_bytes"],
                "estimated_original_tokens": original,
                "estimated_saved_tokens": saved,
                "saved_pct": pct,
            })

        return results

    finally:
        conn.close()


def _aggregate_from_cold(
    date_from: str, date_to: str
) -> list[dict[str, Any]]:
    """Fallback: aggregate directly from ``cold_entries``."""
    db_path = _resolve_db_path()
    if not os.path.exists(db_path):
        return []

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row

    try:
        boot = _boot_epoch()
        rows = conn.execute(
            "SELECT content_type, size_bytes, stored_at FROM cold_entries"
        ).fetchall()

        ag: dict[str, dict[str, Any]] = {}
        for r in rows:
            entry_date = _date.fromtimestamp(
                boot + r["stored_at"]
            ).isoformat()
            if not (date_from <= entry_date <= date_to):
                continue

            ctype = r["content_type"] or "unknown"
            if ctype not in ag:
                ag[ctype] = {"entry_count": 0, "total_size_bytes": 0}
            ag[ctype]["entry_count"] += 1
            ag[ctype]["total_size_bytes"] += (r["size_bytes"] or 0)

        results: list[dict[str, Any]] = []
        for ctype, a in ag.items():
            original = max(1, a["total_size_bytes"] // 4)
            saved_pct = ESTIMATED_SAVED_PCT.get(ctype, 50.0)
            saved = int(original * saved_pct / 100)
            results.append({
                "content_type": ctype,
                "label": TYPE_LABELS.get(ctype, ctype),
                "entry_count": a["entry_count"],
                "total_size_bytes": a["total_size_bytes"],
                "estimated_original_tokens": original,
                "estimated_saved_tokens": saved,
                "saved_pct": saved_pct,
            })

        results.sort(key=lambda x: x["estimated_saved_tokens"], reverse=True)
        return results

    finally:
        conn.close()


def _daily_breakdown(
    date_from: str, date_to: str
) -> list[dict[str, Any]]:
    """Return per-day totals within the range (for multi-day reports)."""
    db_path = _resolve_db_path()
    if not os.path.exists(db_path):
        return []

    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row

    try:
        _ensure_schema(conn)
        rows = conn.execute(
            "SELECT date, "
            "       SUM(entry_count) AS entries, "
            "       SUM(estimated_original_tokens) AS orig_tokens, "
            "       SUM(estimated_saved_tokens) AS saved_tokens "
            "FROM daily_stats "
            "WHERE date >= ? AND date <= ? "
            "GROUP BY date "
            "ORDER BY date ASC",
            (date_from, date_to),
        ).fetchall()

        return [
            {
                "date": r["date"],
                "entry_count": r["entries"],
                "estimated_original_tokens": r["orig_tokens"],
                "estimated_saved_tokens": r["saved_tokens"],
            }
            for r in rows
        ]

    finally:
        conn.close()


# ── Report formatting ───────────────────────────────────────────────────────

def _format_markdown(
    results: list[dict[str, Any]],
    date_label: str,
    db_path: str,
    daily_rows: list[dict[str, Any]] | None = None,
) -> str:
    """Generate a Markdown report."""
    lines: list[str] = []
    lines.append("# Context Compression Daily Report")
    lines.append("")
    lines.append(f"**Period**: {date_label}")
    lines.append(f"**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"**Source**: `daily_stats` @ `{db_path}`")
    lines.append("")

    if not results:
        lines.append(
            "> [WARN] No compression activity recorded for this period."
        )
        lines.append("")
        return "\n".join(lines)

    # ── Summary ──
    total_entries = sum(r["entry_count"] for r in results)
    total_original = sum(r["estimated_original_tokens"] for r in results)
    total_saved = sum(r["estimated_saved_tokens"] for r in results)
    overall_pct = (total_saved / max(1, total_original)) * 100
    est_cost = total_saved / 1_000_000 * COST_PER_M_TOKENS

    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Total auto-cached entries | **{total_entries}** |")
    lines.append(
        f"| Estimated original tokens | **{total_original:,}** |"
    )
    lines.append(
        f"| Estimated tokens saved | **{total_saved:,}** "
        f"({overall_pct:.0f}%) |"
    )
    lines.append(f"| Estimated cost saved | **~${est_cost:.4f}** |")
    lines.append("")

    # ── By content type ──
    lines.append("## By Content Type")
    lines.append("")
    lines.append(
        "| Type | Entries | Original Tokens | Saved Tokens | Saved % |"
    )
    lines.append(
        "|------|---------|-----------------|--------------|---------|"
    )
    for r in results:
        lines.append(
            f"| {r['label']} | {r['entry_count']} | "
            f"{r['estimated_original_tokens']:,} | "
            f"{r['estimated_saved_tokens']:,} | "
            f"{r['saved_pct']:.0f}% |"
        )
    lines.append("")

    # ── Daily breakdown (multi-day only) ──
    if daily_rows and len(daily_rows) > 1:
        lines.append("## Daily Breakdown")
        lines.append("")
        lines.append(
            "| Date | Entries | Orig. Tokens | Saved Tokens | Saved % |"
        )
        lines.append(
            "|------|---------|--------------|--------------|---------|"
        )
        for d in daily_rows:
            d_pct = (
                d["estimated_saved_tokens"]
                / max(1, d["estimated_original_tokens"])
                * 100
            )
            lines.append(
                f"| {d['date']} | {d['entry_count']} | "
                f"{d['estimated_original_tokens']:,} | "
                f"{d['estimated_saved_tokens']:,} | "
                f"{d_pct:.0f}% |"
            )
        lines.append("")

    # ── Storage ──
    total_kb = sum(r["total_size_bytes"] for r in results) / 1024
    lines.append("## Storage")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Cold-store size (period) | **{total_kb:.0f} KB** |")
    lines.append("| TTL | 2 hours |")
    lines.append("| Max cold storage | 200 MB |")
    lines.append("")

    lines.append("---")
    lines.append(
        "*Token estimates: ~4 chars/token original, "
        "empirically-derived compression ratios per content type.*"
    )
    lines.append(
        f"*Run `py daily_report.py --save` to export this report as a file.*"
    )
    lines.append("")

    return "\n".join(lines)


def _format_json(
    results: list[dict[str, Any]],
    date_label: str,
    daily_rows: list[dict[str, Any]] | None = None,
) -> str:
    """Generate a JSON report."""
    total_entries = sum(r["entry_count"] for r in results)
    total_original = sum(r["estimated_original_tokens"] for r in results)
    total_saved = sum(r["estimated_saved_tokens"] for r in results)

    payload: dict[str, Any] = {
        "period": date_label,
        "generated_at": datetime.now().isoformat(),
        "summary": {
            "total_entries": total_entries,
            "estimated_original_tokens": total_original,
            "estimated_saved_tokens": total_saved,
            "saved_pct": round(
                total_saved / max(1, total_original) * 100, 1
            ),
            "estimated_cost_saved_usd": round(
                total_saved / 1_000_000 * COST_PER_M_TOKENS, 4
            ),
        },
        "by_type": [
            {
                "content_type": r["content_type"],
                "entry_count": r["entry_count"],
                "estimated_original_tokens": r["estimated_original_tokens"],
                "estimated_saved_tokens": r["estimated_saved_tokens"],
                "saved_pct": r["saved_pct"],
            }
            for r in results
        ],
    }

    if daily_rows:
        payload["daily_breakdown"] = daily_rows

    return json.dumps(payload, ensure_ascii=False, indent=2)


# ── Main generate function ──────────────────────────────────────────────────

def generate_report(
    date_from: str,
    date_to: str | None = None,
    output_format: str = "markdown",
    save_to_file: bool = False,
) -> str:
    """Generate and optionally save the compression report.

    Args:
        date_from: Start date (YYYY-MM-DD).
        date_to: End date (inclusive).  Defaults to *date_from*.
        output_format: ``"markdown"`` or ``"json"``.
        save_to_file: If True, write to ``reports/`` directory.

    Returns the formatted report string.
    """
    if date_to is None:
        date_to = date_from

    db_path = _resolve_db_path()

    if not os.path.exists(db_path):
        return (
            "# Daily Compression Report\n\n"
            f"> [WARN] Cold store database not found at `{db_path}`.\n"
            f"> No compression data available yet.\n"
        )

    # Label for the report header.
    if date_from == date_to:
        date_label = date_from
    else:
        date_label = f"{date_from} → {date_to}"

    # Query pre-aggregated stats (SQL).
    results = query_stats(date_from, date_to)

    # For multi-day reports, also get daily breakdown.
    daily_rows = None
    if date_from != date_to:
        daily_rows = _daily_breakdown(date_from, date_to)

    # Format.
    if output_format == "json":
        report = _format_json(results, date_label, daily_rows)
    else:
        report = _format_markdown(results, date_label, db_path, daily_rows)

    # Optionally save to file.
    if save_to_file:
        report_dir = _resolve_report_dir()
        os.makedirs(report_dir, exist_ok=True)
        ext = "json" if output_format == "json" else "md"

        # Filename: single-day → compression_report_<date>.md,
        #           range      → compression_report_<from>_<to>.md
        if date_from == date_to:
            stem = f"compression_report_{date_from}"
        else:
            stem = f"compression_report_{date_from}_{date_to}"

        filepath = os.path.join(report_dir, f"{stem}.{ext}")
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(report)
        # Write to stderr to avoid polluting stdout when piped.
        print(f"[daily_report] Saved: {filepath}", file=sys.stderr)

    return report


# ── Utility ─────────────────────────────────────────────────────────────────

def get_yesterday_stats_summary() -> dict[str, Any] | None:
    """Quick DB query for yesterday's summary (used by SessionStart hook)."""
    yesterday = (_date.today() - timedelta(days=1)).isoformat()
    results = query_stats(yesterday, yesterday)
    if not results:
        return None

    total_entries = sum(r["entry_count"] for r in results)
    total_saved = sum(r["estimated_saved_tokens"] for r in results)
    return {
        "date": yesterday,
        "total_entries": total_entries,
        "estimated_saved_tokens": total_saved,
        "by_type": [
            {"type": r["content_type"], "entries": r["entry_count"]}
            for r in results
        ],
    }


# ── CLI ─────────────────────────────────────────────────────────────────────

def _safe_print(text: str) -> None:
    """Print safely on Windows consoles."""
    try:
        print(text)
    except UnicodeEncodeError:
        encoded = text.encode(
            sys.stdout.encoding or "utf-8", errors="replace"
        )
        sys.stdout.buffer.write(encoded + b"\n")
        sys.stdout.flush()


def _parse_range(val: str) -> tuple[str, str]:
    """Parse ``YYYY-MM-DD..YYYY-MM-DD`` into a (from, to) tuple."""
    parts = val.split("..")
    if len(parts) != 2:
        raise argparse.ArgumentTypeError(
            f"Range must be YYYY-MM-DD..YYYY-MM-DD, got: {val}"
        )
    return parts[0].strip(), parts[1].strip()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate daily context-compression report."
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument(
        "--date",
        default=None,
        help="Target date (YYYY-MM-DD).  Default: today.",
    )
    group.add_argument(
        "--week",
        action="store_true",
        help="Report for the current week (Monday → today).",
    )
    group.add_argument(
        "--month",
        action="store_true",
        help="Report for the current month (1st → today).",
    )
    group.add_argument(
        "--range",
        type=_parse_range,
        metavar="FROM..TO",
        help="Custom date range: YYYY-MM-DD..YYYY-MM-DD.",
    )
    parser.add_argument(
        "--json",
        dest="output_format",
        action="store_const",
        const="json",
        default="markdown",
        help="Output JSON instead of Markdown.",
    )
    parser.add_argument(
        "--save",
        action="store_true",
        help="Save report to reports/ directory.",
    )
    parser.add_argument(
        "--persist",
        action="store_true",
        help=(
            "Persist today's raw entries into daily_stats table "
            "(idempotent).  Automatically called by the Stop hook."
        ),
    )
    args = parser.parse_args()

    # --persist mode: write stats and exit.
    if args.persist:
        ok = persist_daily_stats()
        if ok:
            _safe_print("[persist] Today's stats written to daily_stats.")
        else:
            _safe_print(
                "[persist] No database found — nothing to persist."
            )
        return

    # Resolve date range.
    today = _date.today()
    if args.range:
        date_from, date_to = args.range
    elif args.week:
        date_from = (today - timedelta(days=today.weekday())).isoformat()
        date_to = today.isoformat()
    elif args.month:
        date_from = today.replace(day=1).isoformat()
        date_to = today.isoformat()
    elif args.date:
        date_from = args.date
        date_to = args.date
    else:
        date_from = today.isoformat()
        date_to = date_from

    report = generate_report(
        date_from=date_from,
        date_to=date_to,
        output_format=args.output_format,
        save_to_file=args.save,
    )
    _safe_print(report)


if __name__ == "__main__":
    main()
